spring:
 application:
  name: config-client
---
##生产环境
spring:
 profiles:
  active: dev
server:
 port: 9091
app:
 info:
  name: ${spring.application.name}
  port: ${server.port}
  message: 生产环境
---
##开发环境
spring:
 profiles:
  active: prd
server:
 port: 9092
app:
 info:
  name: ${spring.application.name}
  port: ${server.port}
  message: 开发环境